'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:





Triangle

&nbsp;

Tn=n(n+1)/2

&nbsp;

1, 3, 6, 10, 15, ...





Pentagonal

&nbsp;

Pn=n(3n&minus;1)/2

&nbsp;

1, 5, 12, 22, 35, ...





Hexagonal

&nbsp;

Hn=n(2n&minus;1)

&nbsp;

1, 6, 15, 28, 45, ...





It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''