'''
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

oldest = 1
newest = 2
evensSum = 2
while( newest + oldest < 4000000 ):
	total = newest + oldest
	oldest = newest
	newest = total
	if( newest % 2 == 0 ):
		evensSum += newest

print evensSum
